### ISSUE TITLE
Error occured while trying to proxy to: localhost:4001

### ISSUE THREAD

**Issue by andela-akolawole** [teamtaverna/web_client#36]
I get this error every time I run `npm run dev`

**Comment by abiodun0** [comment]
Will look into that later today. What node version are you using?

**Comment by andela-akolawole** [comment]
4.2.6

**Comment by andela-kanyanwu** [comment]
@abiodun0 @andela-akolawole Here is the corresponding card on Trello. https://trello.com/c/bBqhh9Xf/174-error-occured-while-trying-to-proxy-to-localhost-4001 Please move it as appropriate so we can keep track of what is going on easily.

**Comment by abiodun0** [comment]
It requires you to be using node version 6.8 upward @andela-akolawole. kindly upgrade and see if you still have the same problem cc @andela-rsadiq

**Comment by andela-akolawole** [comment]
Thanks :+1:
